version: "3.0"
services:
  core-db:
    build: core-db
    ports:
      - "5433:5432"
#    volumes:
#      - core-db-data:/etc/postgresql/data
#      - core-db-data:/var/log/postgresql
#      - core-db-data:/var/lib/postgresql/data
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
  auth-db:
    build: auth-db
    ports:
      - "5432:5432"
#    volumes:
#      - auth-db-data:/etc/postgresql/data
#      - auth-db-data:/var/log/postgresql
#      - auth-db-data:/var/lib/postgresql/data
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
  auth:
    build: auth
    ports:
      - "3005:3005"
      - "3006:3006"
    volumes:
      - user-images:/usr/src/app/images
    restart: always
    cap_drop:
      - ALL
  payment_core:
    build: payment
    ports:
      - "8082:8080"
    volumes:
      - payment-wallet:/root/.PaymentService
      - m2-repo:/root/.m2
    restart: always
    cap_drop:
      - ALL
  vault:
    build: vault
    ports:
      - "8081:8081"
    volumes:
      - vault-wallet:/root/.Vault
      - m2-repo:/root/.m2
    restart: always
    cap_drop:
      - ALL
  core:
    build: core
    ports:
      - "3002:3002"
    restart: always
    cap_drop:
      - ALL
  jms:
    build: jms
    ports:
      - "3001:3001"
    restart: always
    cap_drop:
      - ALL
  jmw:
    build: jmw
    ports:
      - "3004:3004"
    restart: always
    cap_drop:
      - ALL
  couponserver:
    build: couponserver
    ports:
      - "3010:3010"
    restart: always
    cap_drop:
      - ALL
    volumes:
      - coupon-db:/usr/src/db
  ams:
    build: ams
    ports: "3007:3007"
    restart: always
    cap_drop:
      - ALL

volumes:
  payment-wallet:
  vault-wallet:
  m2-repo:
  user-images:
  coupon-db:
#  auth-db-data:
#  core-db-data:

networks:
  default:
    external:
      name: iuno-network